<section id="home">

	<h1><?php echo $lang['the_big_search_h1'] ?></h1>

	<div class="m0a u66">
    
    <form class="row" action="" method="get">
    	
        <div class="box u66">
        	<input type="text" name="search" placeholder="<?php echo $lang['search_txt']; ?>" style="width: 100%; height: 50px; margin-bottom: 20px" />
        </div>
        <div class="box u33">
        	<input type="submit" class="btn btn-primary" value="<?php echo $lang['search_btn']; ?>" style="width: 100%; height: 50px" />
        </div>
    </form>
    
    </div>
    
</section>