<section id="admin">

	<form class="form u66" action="" method="post">
    
    	<h1><?php echo $lang['album_edit_h1']; ?></h1>
        
		<label for="name"><?php echo $lang['album_name']; ?></label>
		<input class="u33" type="text" name="name" placeholder="<?php echo $lang['album_name']; ?> &hellip;" value="<?php echo $album['name']; ?>" required />
        
		<label for="description"><?php echo $lang['album_description']; ?></label>
		<textarea name="description" placeholder="<?php echo $lang['album_description']; ?> &hellip;"><?php echo $album['description']; ?></textarea>

		<label for="released"><?php echo $lang['album_released']; ?></label>
		<input type="date" name="released" value="<?php echo $album['released']; ?>" required />

		<input type="hidden" name="artiste_id" value="<?php echo $album['artiste_id']; ?>" />
		<input type="hidden" name="id" value="<?php echo htmlentities($_GET['id']); ?>" />
		
		<?php 
		if (isset($categories) and !empty($categories)) {
			
			echo '<label for="category">' . $lang['category_name'] . '</label>';
			echo '<select name="category">';
			
			foreach($categories as $category) {
				echo '	<option value="' . $category['id'] . '"'.($category['id'] == $album['id'] ? ' selected="selected"' : '').'>' . $category['name'] . '</option>';
			}
			
			echo '</select> <a class="btn btn-primary" href="/' . $language . '/admin/album/category">'. $lang['btnAddCat'].'</a>';
			
			echo '<label class="hide">&nbsp;</label>';
			echo '<input type="submit" class="btn btn-primary" value="' . $lang['btnSubmit'] . '" />';
		
		} 
		?>
	</form>

</section>